app/models/collection.py
from app import db
from app.models.abstract import BaseModel
from app.models.enums import Status, PrivacyType
from app.helpers.string_helper import generate_uuid

tags = db.Table(
    "tags",
    db.Column("tag_id", db.ForeignKey("tag.id"), primary_key=True),
    db.Column("collection_id", db.ForeignKey("collection.id"), primary_key=True)
)


class Collection(BaseModel):
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=True)
    user = db.relationship("User", backref="collections")
    title = db.Column(db.String(255), nullable=False)
    description = db.Column(db.Text, nullable=True)
    privacy = db.Column(db.Enum(PrivacyType), nullable=True, default=PrivacyType.private)
    status = db.Column(db.Enum(Status), nullable=False, default=Status.active)
    uuid = db.Column(db.String(32), nullable=False, default=generate_uuid)
    tags = db.relationship("Tag", secondary=tags, lazy="subquery", backref=db.backref("collections", lazy=True))

    def __repr__(self):
        return "Collection({})".format(self.title)


class Snippet(BaseModel):
    collection_id = db.Column(db.Integer, db.ForeignKey("collection.id"), nullable=True)
    collection = db.relationship("Collection", backref="snippets")
    name = db.Column(db.String(50), nullable=False)
    language = db.Column(db.String(10), nullable=False)  # this field may be enum.
    content = db.Column(db.Text, nullable=True)
    privacy = db.Column(db.Enum(PrivacyType), nullable=True, default=PrivacyType.private)
    status = db.Column(db.Enum(Status), nullable=False, default=Status.active)
    uuid = db.Column(db.String(32), nullable=False, default=generate_uuid)

    def __repr__(self):
        return "Snippet({} -> {})".format(self.collection.title, self.name)


class Tag(BaseModel):
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=True)
    user = db.relationship("User", backref="tags")
    name = db.Column(db.String(50), nullable=False)
    color = db.Column(db.String(7), nullable=True)
    privacy = db.Column(db.Enum(PrivacyType), nullable=True, default=PrivacyType.private)
    uuid = db.Column(db.String(32), nullable=False, default=generate_uuid)

    def active_collection_count(self):
        total_active_collection = (
            Collection.query
            .join(tags)
            .filter((tags.c.collection_id == Collection.id) & (tags.c.tag_id == self.id))
            .filter(Collection.status == Status.active)
            .count()
        )
        return total_active_collection

    def __repr__(self):
        return "Tag({})".format(self.name)


class Comment(BaseModel):
    collection_id = db.Column(db.Integer, db.ForeignKey("collection.id"), nullable=False)
    collection = db.relationship("Collection", backref="comments")
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=True)
    user = db.relationship("User")
    content = db.Column(db.Text, nullable=False)
    status = db.Column(db.Enum(Status), nullable=False, default=Status.active)

app/forms/collection.py
from flask_wtf import FlaskForm
from wtforms import (
    Form, StringField,
    TextAreaField,
    SelectField,
    SubmitField,
    SelectMultipleField,
    FieldList,
    FormField,
)
from wtforms.validators import DataRequired, Optional, Length
from wtforms.widgets import ListWidget, CheckboxInput


from app.models.enums import PrivacyType, LangType


class MultiCheckboxField(SelectMultipleField):
    widget = ListWidget(prefix_label=False)
    option_widget = CheckboxInput()


class SnippetForm(Form):
    file_name = StringField(
        "Snippet Name",
        validators=[DataRequired()],
        render_kw={"placeholder": "Snippet Name"}
    )
    file_lang = SelectField(
        "Snippet Lang",  # or ext.
        validators=[DataRequired()],
        choices=[
            (LangType.text.name, LangType.text.value),
            (LangType.markdown.name, LangType.markdown.value),
            (LangType.html.name, LangType.html.value),
            (LangType.python.name, LangType.python.value),
            (LangType.php.name, LangType.php.value),
            (LangType.sql.name, LangType.sql.value),
            (LangType.javascript.name, LangType.javascript.value),
            (LangType.go.name, LangType.go.value),
        ],
        render_kw={"placeholder": "Snippet Lang"},
    )
    content = TextAreaField(
        "Snippet Content",
        validators=[DataRequired()],
        render_kw={"placeholder": "Snippet Content"}
    )


class CreateCollectionForm(FlaskForm):
    title = StringField(
        "Collection Title",
        validators=[DataRequired(), Length(min=3, max=255)]
    )
    description = TextAreaField("Description")
    privacy = SelectField(
        "Privacy",
        validators=[DataRequired()],
        choices=[
            (PrivacyType.private.name, PrivacyType.private.value),
            (PrivacyType.public.name, PrivacyType.public.value),
        ]
    )
    tags = MultiCheckboxField(
        "Tags",
        validators=[Optional()],
        coerce=int,
    )
    snippets = FieldList(FormField(SnippetForm), min_entries=1, max_entries=20)

    submit = SubmitField("Save")


class UpdateCollectionForm(FlaskForm):
    title = StringField(
        "Collection Title",
        validators=[DataRequired(), Length(min=3, max=255)]
    )
    description = TextAreaField("Description")
    privacy = SelectField(
        "Privacy",
        validators=[DataRequired()],
        choices=[
            (PrivacyType.public.name, PrivacyType.public.value),
            (PrivacyType.private.name, PrivacyType.private.value)
        ]
    )
    tags = MultiCheckboxField(
        "Tags",
        validators=[Optional()],
        coerce=int,
    )

    submit = SubmitField("Save")


class CreateSnippetForm(FlaskForm):
    name = StringField(
        "Snippet Name",
        validators=[DataRequired()],
        render_kw={"placeholder": "Snippet Name"}
    )
    language = SelectField(
        "Snippet  Language",
        validators=[DataRequired()],
        choices=[
            (LangType.text.name, LangType.text.value),
            (LangType.markdown.name, LangType.markdown.value),
            (LangType.html.name, LangType.html.value),
            (LangType.python.name, LangType.python.value),
            (LangType.php.name, LangType.php.value),
            (LangType.sql.name, LangType.sql.value),
            (LangType.javascript.name, LangType.javascript.value),
            (LangType.go.name, LangType.go.value),
        ],
    )
    privacy = SelectField(
        "Snippet  Privacy",
        validators=[DataRequired()],
        choices=[
            (PrivacyType.private.name, PrivacyType.private.value),
            (PrivacyType.public.name, PrivacyType.public.value),
        ],
    )
    content = TextAreaField(
        "Snippet Content",
        validators=[DataRequired()],
        render_kw={"placeholder": "Snippet Content"}
    )
    submit = SubmitField("Save")


class CreateTagForm(FlaskForm):
    name = StringField(
        "Tag Name",
        validators=[DataRequired(), Length(min=1, max=50)],

    )
    color = SelectField(
        "Tag Color",
        validators=[Optional()],
        choices=[
            ("red", "Red"),
            ("blue", "Blue"),
            ("green", "Green"),
            ("purple", "Purple"),
        ]
    )
    privacy = SelectField(
        "Privacy",
        validators=[DataRequired()],
        choices=[
            (PrivacyType.private.name, PrivacyType.private.value),
            (PrivacyType.public.name, PrivacyType.public.value),
        ]
    )
    submit = SubmitField("Save")

app/routes/collection.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user
from sqlalchemy import func

from app import db
from app.models.enums import Status, PrivacyType
from app.models.collection import Collection, Snippet, Tag
from app.forms.collection import (
    CreateSnippetForm,
    CreateTagForm,
    CreateCollectionForm,
    SnippetForm,
    UpdateCollectionForm,
)
from app.helpers.string_helper import generate_uuid

collection = Blueprint("collection", __name__, url_prefix="/collection")


@collection.route("/")
@collection.route("/index")
@login_required
def collection_index():
    filter_array = []

    if request.args.get("tag", None):
        filter_array.append(
            Collection.tags.any(Tag.name == request.args.get("tag"))
        )

    if request.args.get("type", None):
        filter_array.append(~Collection.tags.any())

    the_collections = (
        Collection.query
        .filter_by(user=current_user)
        .filter_by(status=Status.active)
        .filter(*filter_array)
        .order_by(Collection.updated_at.desc())
        .all()
    )

    return render_template(
        "views/collection/collection_index.html",
        title="My Collections",
        the_collections=the_collections,
    )


@collection.route("/create", methods=["GET", "POST"])
@login_required
def collection_create():
    form = CreateCollectionForm()
    sub_form = SnippetForm(prefix="snippets-_-")
    the_tags = Tag.query.filter_by(user=current_user).all()
    form.tags.choices = [(i.id, i.name) for i in the_tags]

    if form.validate_on_submit():
        new_collection = Collection()
        new_collection.user = current_user
        new_collection.title = form.title.data
        new_collection.description = form.description.data
        new_collection.privacy = form.privacy.data
        new_collection.uuid = generate_uuid(Collection)

        db.session.add(new_collection)
        db.session.flush()

        for _snippet in form.snippets.data:
            new_snippet = Snippet()
            new_snippet.collection = new_collection
            new_snippet.name = _snippet["file_name"]
            new_snippet.language = _snippet["file_lang"]
            new_snippet.content = _snippet["content"]
            new_snippet.uuid = generate_uuid(Snippet)

            db.session.add(new_snippet)

        for _tag in form.tags.data:
            tag_check = Tag.query.filter_by(id=_tag).filter_by(user=current_user).first()

            if tag_check:
                new_collection.tags.append(tag_check)
                db.session.flush()

        db.session.commit()

        return redirect(url_for("collection.collection_detail", uuid=new_collection.uuid))

    form.tags.choices = [(i.id, i.name) for i in the_tags]

    return render_template(
        "views/collection/collection_create.html",
        title="Collection Create",
        form=form,
        sub_form=sub_form,
    )


@collection.route("/detail/<string:uuid>")
@login_required
def collection_detail(uuid):
    the_collection = (
        Collection.query
        .filter_by(user=current_user)
        .filter_by(status=Status.active)
        .filter_by(uuid=uuid)
        .first_or_404()
    )

    the_snippets = (
        Snippet.query
        .filter_by(collection=the_collection)
        .filter_by(status=Status.active)
        .all()
    )

    return render_template(
        "views/collection/collection_detail.html",
        title="Collection: {}".format(the_collection.title),
        the_collection=the_collection,
        the_snippets=the_snippets,
    )


@collection.route("/detail/<string:uuid>/edit", methods=["GET", "POST"])
@login_required
def collection_update(uuid):
    the_collection = (
        Collection.query
        .filter_by(uuid=uuid)
        .filter_by(user=current_user)
        .filter_by(status=Status.active)
        .first_or_404()
    )

    form = UpdateCollectionForm()
    the_tags = Tag.query.filter_by(user=current_user).all()
    form.tags.choices = [(i.id, i.name) for i in the_tags]

    if form.validate_on_submit():
        the_collection.title = form.title.data
        the_collection.description = form.description.data
        the_collection.privacy = form.privacy.data
        the_collection.tags = []

        for _tag in form.tags.data:
            tag_check = Tag.query.filter_by(id=_tag).filter_by(user=current_user).first()

            if tag_check:
                the_collection.tags.append(tag_check)
                db.session.flush()

        the_collection.save()

        flash("Collection Successfully Updated", "success")

    form.title.data = the_collection.title
    form.description.data = the_collection.description
    form.privacy.data = the_collection.privacy.name
    form.tags.data = [i.id for i in the_collection.tags]

    return render_template(
        "views/collection/collection_update.html",
        title="Collection Edit: {}".format(the_collection.title),
        form=form,
        the_collection=the_collection,
    )


@collection.route("/detail/<string:uuid>/delete", methods=["DELETE"])
@login_required
def collection_delete(uuid):
    the_collection = (
        Collection.query
        .filter_by(user=current_user)
        .filter_by(status=Status.active)
        .filter_by(uuid=uuid)
        .first_or_404()
    )

    the_collection.status = Status.deleted
    the_collection.save()

    return {"message": "Collection Successfully Deleted"}


@collection.route("/detail/<string:uuid>/snippet_create", methods=["GET", "POST"])
@login_required
def snippet_create(uuid):
    the_collection = (
        Collection.query
        .filter_by(user=current_user)
        .filter_by(status=Status.active)
        .filter_by(uuid=uuid)
        .first_or_404()
    )

    form = CreateSnippetForm()

    if form.validate_on_submit():
        the_snippet = Snippet()
        the_snippet.collection = the_collection
        the_snippet.name = form.name.data
        the_snippet.language = form.language.data
        the_snippet.content = form.content.data
        the_snippet.privacy = form.privacy.data
        the_snippet.uuid = generate_uuid(Snippet)
        the_snippet.save()

        flash("Snippet Successfully Updated", "success")

        return redirect(url_for("collection.snippet_detail", uuid=the_snippet.uuid))

    return render_template(
        "views/collection/snippet_create.html",
        title="Create Snippet: {}".format(the_collection.title),
        form=form,
        the_collection=the_collection,
    )


@collection.route("/snippet/detail/<string:uuid>", methods=["GET", "POST"])
@login_required
def snippet_detail(uuid):
    the_snippet = (
        Snippet.query
        .filter_by(uuid=uuid)
        .filter_by(status=Status.active)
        .filter(Snippet.collection.has(user=current_user))
        .first_or_404()
    )

    form = CreateSnippetForm()

    if form.validate_on_submit():
        the_snippet.name = form.name.data
        the_snippet.language = form.language.data
        the_snippet.privacy = form.privacy.data
        the_snippet.content = form.content.data
        the_snippet.save()

        flash("Snippet Successfully Updated", "success")

    form.name.data = the_snippet.name
    form.language.data = the_snippet.language
    form.privacy.data = the_snippet.privacy.name
    form.content.data = the_snippet.content

    return render_template(
        "views/collection/snippet_detail.html",
        title="Snippet: {}".format(the_snippet.name),
        the_snippet=the_snippet,
        form=form,
    )


@collection.route("/snippet/detail/<string:uuid>/public")
def snippet_detail_public(uuid):
    the_snippet = (
        Snippet.query
        .filter_by(uuid=uuid)
        .filter_by(status=Status.active)
        .filter_by(privacy=PrivacyType.public)
        .first_or_404()
    )

    return render_template(
        "views/collection/snippet_detail_public.html",
        title="Snippet: {}".format(the_snippet.name),
        the_snippet=the_snippet,
    )


@collection.route("/snippet/detail/<string:uuid>/public/raw")
def snippet_detail_raw(uuid):
    the_snippet = (
        Snippet.query
        .filter_by(uuid=uuid)
        .filter_by(status=Status.active)
        .filter_by(privacy=PrivacyType.public)
        .first_or_404()
    )

    return render_template(
        "views/collection/snippet_detail_raw.html",
        title="Snippet: {}".format(the_snippet.name),
        the_snippet=the_snippet,
    )


@collection.route("/snippet/detail/<string:uuid>/delete", methods=["DELETE"])
@login_required
def snippet_delete(uuid):
    the_snippet = (
        Snippet.query
        .filter_by(uuid=uuid)
        .filter_by(status=Status.active)
        .filter(Snippet.collection.has(user=current_user))
        .first_or_404()
    )

    the_snippet.status = Status.deleted
    the_snippet.save()

    return {"message": "Snippet Successfully Deleted"}


@collection.route("/tag/", methods=["GET", "POST"])
@collection.route("/tag/index", methods=["GET", "POST"])
@login_required
def tag_index():
    form = CreateTagForm()

    if form.validate_on_submit():
        tag_check = (
            Tag.query
            .filter(func.lower(Tag.name) == func.lower(form.name.data.strip()))
            .filter_by(user=current_user)
            .first()
        )

        if tag_check:
            flash("This Tag Already Exists", "danger")
        else:
            the_tag = Tag()
            the_tag.user = current_user
            the_tag.name = form.name.data.strip()
            the_tag.color = form.color.data
            the_tag.privacy = form.privacy.data
            the_tag.uuid = generate_uuid(Tag)
            the_tag.save()

            flash("Tag Created Successfully", "success")

    the_tags = Tag.query.filter_by(user=current_user).all()

    return render_template(
        "views/collection/tag_index.html",
        title="Tag Management",
        the_tags=the_tags,

app/templates/views/collection/collection_detail.html
{% extends "assets/bases/app.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-6">
            <b>Title:</b> {{ the_collection.title }} <b>by</b> {{ the_collection.user.username }}<br>
            <b>Description:</b> {{ the_collection.description }}<br>
            <b>Created / Updated:</b> {{ the_collection.created_at }} / {{ the_collection.updated_at }}<br>
            <b>Privacy:</b> {{ the_collection.privacy.value }}<br>
            <b>Tag(s):</b>
            <p>
                {% for tag in the_collection.tags %}
                    <div class="label label-primary">{{ tag.name }}</div>
                {% endfor %}
            </p>
        </div>
        <div class="col-md-6 text-right">
            <a href="{{ url_for("collection.snippet_create", uuid=the_collection.uuid) }}" class="btn btn-default btn-icon">Add Snippet<i class="entypo-list-add"></i></a>
            <a href="{{ url_for("collection.collection_update", uuid=the_collection.uuid) }}" class="btn btn-blue btn-icon">Edit Collection<i class="entypo-pencil"></i></a>
            <button type="button" onclick="delete_collection()" class="btn btn-red btn-icon">Delete Collection<i class="entypo-cancel"></i></button>
        </div>
    </div>
    <hr>
    {% for snippet in the_snippets %}
        <div class="panel panel-primary" data-collapsed="{{ loop.index0 }}"> <!-- data-collapsed="0" -->
            <div class="panel-heading">
                <div class="panel-title">{{ snippet.name }} ({{ snippet.language }}) -> {{ snippet.privacy.value }}</div>
                <div class="panel-options">
                    <a href="{{ url_for("collection.snippet_detail", uuid=snippet.uuid) }}"><i class="entypo-pencil"></i></a>
                    <a href="#" data-rel="collapse"><i class="entypo-down-open"></i></a>
                    <a href="#" data-rel="close"><i class="entypo-cancel"></i></a>
                </div>
            </div>
            <div class="panel-body">
                <pre><code class="language-{{ snippet.language }}">{{ snippet.content | e }}</code></pre>
            </div>
        </div>
    {% endfor %}
{% endblock %}


{% block js %}
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        function delete_collection() {
            Swal.fire({
                title: "Are you sure?",
                text: "You won't be able to revert this!",
                icon: "warning",
                showCancelButton: true,
                confirmButtonColor: "#3085d6",
                cancelButtonColor: "#d33",
                confirmButtonText: "Yes, delete it!"
            }).then((result) => {
                if (result.isConfirmed) {
                    $.ajax({
                        url: "{{ url_for("collection.collection_delete", uuid=the_collection.uuid) }}",
                        method: 'DELETE',
                        dataType: 'json',
                        error: function () {
                            alert("An Error Occoured!");
                        },
                        success: function (response) {
                            Swal.fire(
                                "Deleted!",
                                "Your file has been deleted.",
                                "success"
                            )
                            window.location.href = "{{ url_for("collection.collection_index") }}";
                        }
                    });

                }
            })
        }
    </script>
    <script>hljs.initHighlightingOnLoad();</script>
{% endblock %}


{% block css %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.0/styles/default.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.0/highlight.min.js"></script>
<!-- and it's easy to individually load additional languages -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.0/languages/go.min.js"></script>
{% endblock %}

app/templates/views/collection/snippet_detail.html
{% extends "assets/bases/app.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            {{ error(form) }}
            {{ alert() }}
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <b>Collection:</b> {{ the_snippet.collection.title }}<br>
            <b>Created / Updated:</b> {{ the_snippet.created_at }} / {{ the_snippet.updated_at }}<br>
            <b>Privacy:</b> {{ the_snippet.privacy.value }}<br>
            {% if the_snippet.privacy.name == "public" %}
                <b>Detail Link:</b> <a href="{{ url_for("collection.snippet_detail_public", uuid=the_snippet.uuid) }}">{{ config["SITE_URL"] }}{{ url_for("collection.snippet_detail_public", uuid=the_snippet.uuid) }}</a><br>
                <b>Raw Link:</b> <a href="{{ url_for("collection.snippet_detail_raw", uuid=the_snippet.uuid) }}">{{ config["SITE_URL"] }}{{ url_for("collection.snippet_detail_raw", uuid=the_snippet.uuid) }}</a><br>
            {% endif %}
        </div>
        <div class="col-md-6 text-right">
            <a href="{{ url_for("collection.collection_detail", uuid=the_snippet.collection.uuid) }}" class="btn btn-default btn-icon icon-left">Go To Collection <i class="entypo-left-circled"></i></a>
            <button type="button" onclick="delete_snippet()" class="btn btn-red btn-icon">Delete Snippet<i class="entypo-cancel"></i></button>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-primary" data-collapsed="0">
                <div class="panel-heading">
                    <div class="panel-title">Update Snippet</div>
                </div>
                <div class="panel-body">
                    <form action="" method="POST">
                        {{ form.csrf_token() }}
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    {{ form.name.label(class="control-label") }}
                                    {{ form.name(class="form-control") }}
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    {{ form.language.label(class="control-label") }}
                                    {{ form.language(class="form-control") }}
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    {{ form.privacy.label(class="control-label") }}
                                    {{ form.privacy(class="form-control") }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    {{ form.content.label(class="control-label") }}
                                    {{ form.content(class="form-control", rows=15) }}
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            {{ form.submit(class="btn btn-primary btn-block") }}
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        function delete_snippet() {
            Swal.fire({
                title: "Are you sure?",
                text: "You won't be able to revert this!",
                icon: "warning",
                showCancelButton: true,
                confirmButtonColor: "#3085d6",
                cancelButtonColor: "#d33",
                confirmButtonText: "Yes, delete it!"
            }).then((result) => {
                if (result.isConfirmed) {
                    $.ajax({
                        url: "{{ url_for("collection.snippet_delete", uuid=the_snippet.uuid) }}",
                        method: 'DELETE',
                        dataType: 'json',
                        error: function () {
                            alert("An Error Occoured!");
                        },
                        success: function (response) {
                            Swal.fire(
                                "Deleted!",
                                "Your file has been deleted.",
                                "success"
                            )
                            window.location.href = "{{ url_for("collection.collection_detail", uuid=the_snippet.collection.uuid) }}";
                        }
                    });

                }
            })
        }
    </script>
{% endblock %}

app/templates/views/collection/snippet_detail_public.html
{% extends "assets/bases/base.html" %}

{% block content %}
    <b>Author: </b> {{ the_snippet.collection.user.username }}<br>
    <b>Created / Updated Date: </b> {{ the_snippet.created_at }} / {{ the_snippet.updated_at }}
    <hr>
    <pre><code class="language-{{ the_snippet.language }}">{{ the_snippet.content | e }}</code></pre>
{% endblock %}


{% block js %}
    <script>hljs.initHighlightingOnLoad();</script>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.0/styles/default.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.0/highlight.min.js"></script>
<!-- and it's easy to individually load additional languages -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.0/languages/go.min.js"></script>
{% endblock %}

app/templates/views/collection/tag_detail.html
{% extends "assets/bases/app.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            {{ error(form) }}
            {{ alert() }}
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <div class="panel panel-primary" data-collapsed="0">
                <!-- panel head -->
                <div class="panel-heading">
                    <div class="panel-title">Update Tag</div>
                </div>
                <!-- panel body -->
                <div class="panel-body">
                    <form action="" method="POST">
                        {{ form.csrf_token() }}
                        <div class="form-group">
                            {{ form.name.label(class="control-label") }}
                            {{ form.name(class="form-control") }}
                        </div>
                        <div class="form-group">
                            {{ form.privacy.label(class="control-label") }}
                            {{ form.privacy(class="form-control") }}
                        </div>
                        <div class="form-group">
                            {{ form.color.label(class="control-label") }}
                            {{ form.color(class="form-control") }}
                        </div>
                        <div class="form-group">
                            {{ form.submit(class="btn btn-primary btn-block") }}
                        </div>
                    </form>
                    <button type="button" onclick="delete_tag()" class="btn btn-red btn-block">Delete Tag
                    </button>
                </div>
            </div>
        </div>
        <div class="col-md-9">
            <div class="panel panel-primary" data-collapsed="0">
                <!-- panel head -->
                <div class="panel-heading">
                    <div class="panel-title">Tags</div>
                </div>
                <!-- panel body -->
                <div class="panel-body">
                    <ul class="list-group">
                        {% for tag in tags %}
                            <li class="list-group-item">
                                <span class="badge badge-primary">{{ tag.active_collection_count() }}</span>
                                <a href="{{ url_for("collection.tag_detail", uuid=tag.uuid) }}">
                                    {{ tag.name }} ({{ tag.privacy.value }})
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        function delete_tag(tid) {
            Swal.fire({
                title: "Are you sure?",
                text: "You won't be able to revert this! This tag will be deleted from all collections to which it is linked.",
                icon: "warning",
                showCancelButton: true,
                confirmButtonColor: "#3085d6",
                cancelButtonColor: "#d33",
                confirmButtonText: "Yes, delete it!"
            }).then((result) => {
                if (result.isConfirmed) {
                    $.ajax({
                        url: "{{ url_for("collection.tag_delete", uuid=the_tag.uuid) }}",
                        method: 'DELETE',
                        dataType: 'json',
                        error: function () {
                            alert("An error occoured!");
                        },
                        success: function (response) {
                            Swal.fire(
                                "Deleted!",
                                "Your file has been deleted.",
                                "success"
                            )
                            window.location.href = "{{ url_for("collection.tag_index") }}";
                        }
                    });

                }
            })
        }
    </script>
{% endblock %}