app/routes/auth.py
from flask import Blueprint, redirect, url_for, render_template, flash
from flask_login import current_user, login_user, logout_user

from app.models.user import User
from app.forms.auth import LoginForm, RegisterForm

auth = Blueprint("auth", __name__, url_prefix="/auth")


@auth.route("/")
@auth.route("/index")
def index():
    return redirect(url_for("auth.login"))


@auth.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))

    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is not None and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            return redirect(url_for("main.index"))
        else:
            flash("Login Failed", "danger")

    return render_template("views/auth/login.html", title="Login", form=form)


@auth.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))

    form = RegisterForm()

    if form.validate_on_submit():
        user = User()
        user.first_name = form.first_name.data
        user.last_name = form.last_name.data
        user.username = form.username.data
        user.email = form.email.data
        user.generate_password_hash(form.password.data)
        user.save()

        login_user(user)

        return redirect(url_for("main.index"))

    return render_template("views/auth/register.html", title="Register", form=form)


@auth.route("/logout")
def logout():
    logout_user()
    flash("Logged Out", "success")
    return redirect(url_for("auth.login"))

app/routes/collection.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user
from sqlalchemy import func

from app import db
from app.models.enums import Status, PrivacyType
from app.models.collection import Collection, Snippet, Tag
from app.forms.collection import (
    CreateSnippetForm,
    CreateTagForm,
    CreateCollectionForm,
    SnippetForm,
    UpdateCollectionForm,
)
from app.helpers.string_helper import generate_uuid

collection = Blueprint("collection", __name__, url_prefix="/collection")


@collection.route("/")
@collection.route("/index")
@login_required
def collection_index():
    filter_array = []

    if request.args.get("tag", None):
        filter_array.append(
            Collection.tags.any(Tag.name == request.args.get("tag"))
        )

    if request.args.get("type", None):
        filter_array.append(~Collection.tags.any())

    the_collections = (
        Collection.query
        .filter_by(user=current_user)
        .filter_by(status=Status.active)
        .filter(*filter_array)
        .order_by(Collection.updated_at.desc())
        .all()
    )

    return render_template(
        "views/collection/collection_index.html",
        title="My Collections",
        the_collections=the_collections,
    )


@collection.route("/create", methods=["GET", "POST"])
@login_required
def collection_create():
    form = CreateCollectionForm()
    sub_form = SnippetForm(prefix="snippets-_-")
    the_tags = Tag.query.filter_by(user=current_user).all()
    form.tags.choices = [(i.id, i.name) for i in the_tags]

    if form.validate_on_submit():
        new_collection = Collection()
        new_collection.user = current_user
        new_collection.title = form.title.data
        new_collection.description = form.description.data
        new_collection.privacy = form.privacy.data
        new_collection.uuid = generate_uuid(Collection)

        db.session.add(new_collection)
        db.session.flush()

        for _snippet in form.snippets.data:
            new_snippet = Snippet()
            new_snippet.collection = new_collection
            new_snippet.name = _snippet["file_name"]
            new_snippet.language = _snippet["file_lang"]
            new_snippet.content = _snippet["content"]
            new_snippet.uuid = generate_uuid(Snippet)

            db.session.add(new_snippet)

        for _tag in form.tags.data:
            tag_check = Tag.query.filter_by(id=_tag).filter_by(user=current_user).first()

            if tag_check:
                new_collection.tags.append(tag_check)
                db.session.flush()

        db.session.commit()

        return redirect(url_for("collection.collection_detail", uuid=new_collection.uuid))

    form.tags.choices = [(i.id, i.name) for i in the_tags]

    return render_template(
        "views/collection/collection_create.html",
        title="Collection Create",
        form=form,
        sub_form=sub_form,
    )


@collection.route("/detail/<string:uuid>")
@login_required
def collection_detail(uuid):
    the_collection = (
        Collection.query
        .filter_by(user=current_user)
        .filter_by(status=Status.active)
        .filter_by(uuid=uuid)
        .first_or_404()
    )

    the_snippets = (
        Snippet.query
        .filter_by(collection=the_collection)
        .filter_by(status=Status.active)
        .all()
    )

    return render_template(
        "views/collection/collection_detail.html",
        title="Collection: {}".format(the_collection.title),
        the_collection=the_collection,
        the_snippets=the_snippets,
    )


@collection.route("/detail/<string:uuid>/edit", methods=["GET", "POST"])
@login_required
def collection_update(uuid):
    the_collection = (
        Collection.query
        .filter_by(uuid=uuid)
        .filter_by(user=current_user)
        .filter_by(status=Status.active)
        .first_or_404()
    )

    form = UpdateCollectionForm()
    the_tags = Tag.query.filter_by(user=current_user).all()
    form.tags.choices = [(i.id, i.name) for i in the_tags]

    if form.validate_on_submit():
        the_collection.title = form.title.data
        the_collection.description = form.description.data
        the_collection.privacy = form.privacy.data
        the_collection.tags = []

        for _tag in form.tags.data:
            tag_check = Tag.query.filter_by(id=_tag).filter_by(user=current_user).first()

            if tag_check:
                the_collection.tags.append(tag_check)
                db.session.flush()

        the_collection.save()

        flash("Collection Successfully Updated", "success")

    form.title.data = the_collection.title
    form.description.data = the_collection.description
    form.privacy.data = the_collection.privacy.name
    form.tags.data = [i.id for i in the_collection.tags]

    return render_template(
        "views/collection/collection_update.html",
        title="Collection Edit: {}".format(the_collection.title),
        form=form,
        the_collection=the_collection,
    )


@collection.route("/detail/<string:uuid>/delete", methods=["DELETE"])
@login_required
def collection_delete(uuid):
    the_collection = (
        Collection.query
        .filter_by(user=current_user)
        .filter_by(status=Status.active)
        .filter_by(uuid=uuid)
        .first_or_404()
    )

    the_collection.status = Status.deleted
    the_collection.save()

    return {"message": "Collection Successfully Deleted"}


@collection.route("/detail/<string:uuid>/snippet_create", methods=["GET", "POST"])
@login_required
def snippet_create(uuid):
    the_collection = (
        Collection.query
        .filter_by(user=current_user)
        .filter_by(status=Status.active)
        .filter_by(uuid=uuid)
        .first_or_404()
    )

    form = CreateSnippetForm()

    if form.validate_on_submit():
        the_snippet = Snippet()
        the_snippet.collection = the_collection
        the_snippet.name = form.name.data
        the_snippet.language = form.language.data
        the_snippet.content = form.content.data
        the_snippet.privacy = form.privacy.data
        the_snippet.uuid = generate_uuid(Snippet)
        the_snippet.save()

        flash("Snippet Successfully Updated", "success")

        return redirect(url_for("collection.snippet_detail", uuid=the_snippet.uuid))

    return render_template(
        "views/collection/snippet_create.html",
        title="Create Snippet: {}".format(the_collection.title),
        form=form,
        the_collection=the_collection,
    )


@collection.route("/snippet/detail/<string:uuid>", methods=["GET", "POST"])
@login_required
def snippet_detail(uuid):
    the_snippet = (
        Snippet.query
        .filter_by(uuid=uuid)
        .filter_by(status=Status.active)
        .filter(Snippet.collection.has(user=current_user))
        .first_or_404()
    )

    form = CreateSnippetForm()

    if form.validate_on_submit():
        the_snippet.name = form.name.data
        the_snippet.language = form.language.data
        the_snippet.privacy = form.privacy.data
        the_snippet.content = form.content.data
        the_snippet.save()

        flash("Snippet Successfully Updated", "success")

    form.name.data = the_snippet.name
    form.language.data = the_snippet.language
    form.privacy.data = the_snippet.privacy.name
    form.content.data = the_snippet.content

    return render_template(
        "views/collection/snippet_detail.html",
        title="Snippet: {}".format(the_snippet.name),
        the_snippet=the_snippet,
        form=form,
    )


@collection.route("/snippet/detail/<string:uuid>/public")
def snippet_detail_public(uuid):
    the_snippet = (
        Snippet.query
        .filter_by(uuid=uuid)
        .filter_by(status=Status.active)
        .filter_by(privacy=PrivacyType.public)
        .first_or_404()
    )

    return render_template(
        "views/collection/snippet_detail_public.html",
        title="Snippet: {}".format(the_snippet.name),
        the_snippet=the_snippet,
    )


@collection.route("/snippet/detail/<string:uuid>/public/raw")
def snippet_detail_raw(uuid):
    the_snippet = (
        Snippet.query
        .filter_by(uuid=uuid)
        .filter_by(status=Status.active)
        .filter_by(privacy=PrivacyType.public)
        .first_or_404()
    )

    return render_template(
        "views/collection/snippet_detail_raw.html",
        title="Snippet: {}".format(the_snippet.name),
        the_snippet=the_snippet,
    )


@collection.route("/snippet/detail/<string:uuid>/delete", methods=["DELETE"])
@login_required
def snippet_delete(uuid):
    the_snippet = (
        Snippet.query
        .filter_by(uuid=uuid)
        .filter_by(status=Status.active)
        .filter(Snippet.collection.has(user=current_user))
        .first_or_404()
    )

    the_snippet.status = Status.deleted
    the_snippet.save()

    return {"message": "Snippet Successfully Deleted"}


@collection.route("/tag/", methods=["GET", "POST"])
@collection.route("/tag/index", methods=["GET", "POST"])
@login_required
def tag_index():
    form = CreateTagForm()

    if form.validate_on_submit():
        tag_check = (
            Tag.query
            .filter(func.lower(Tag.name) == func.lower(form.name.data.strip()))
            .filter_by(user=current_user)
            .first()
        )

        if tag_check:
            flash("This Tag Already Exists", "danger")
        else:
            the_tag = Tag()
            the_tag.user = current_user
            the_tag.name = form.name.data.strip()
            the_tag.color = form.color.data
            the_tag.privacy = form.privacy.data
            the_tag.uuid = generate_uuid(Tag)
            the_tag.save()

            flash("Tag Created Successfully", "success")

    the_tags = Tag.query.filter_by(user=current_user).all()

    return render_template(
        "views/collection/tag_index.html",
        title="Tag Management",
        the_tags=the_tags,

app/routes/main.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import current_user

main = Blueprint("main", __name__, url_prefix="/")


@main.route("/")
@main.route("/index")
def index():
    if current_user.is_authenticated:
        return redirect(url_for("collection.collection_index"))
    
    return render_template("views/main/index.html", title="Home")


@main.route("/about")
def about():
    return render_template("views/main/about.html", title="About")


@main.route("/public_collections")
def public_collections():
    return render_template("views/main/public_collections.html", title="Public Collections")

app/routes/profile.py
from flask import Blueprint, render_template, flash
from flask_login import login_required, current_user

from app.models.user import User
from app.forms.profile import EditProfileForm, ChangePasswordForm

profile = Blueprint("profile", __name__, url_prefix="/profile")


@profile.route("/index", methods=["GET", "POST"])
@login_required
def index():
    form = EditProfileForm()

    if form.validate_on_submit():
        user = User.query.filter_by(id=current_user.id).first()

        current_user.first_name = form.first_name.data
        current_user.last_name = form.last_name.data
        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.note = form.note.data
        user.save()

        flash("Profile Successfully Updated", "success")

    form.first_name.data = current_user.first_name
    form.last_name.data = current_user.last_name
    form.username.data = current_user.username
    form.email.data = current_user.email
    form.note.data = current_user.note

    return render_template("views/profile/index.html", title="Edit Profile", form=form)


@profile.route("/password", methods=["GET", "POST"])
@login_required
def password():
    form = ChangePasswordForm()

    if form.validate_on_submit():
        user = User.query.filter_by(id=current_user.id).first()

        user.generate_password_hash(form.new_password.data)
        user.save()

        flash("Password Successfully Updated", "success")

    return render_template("views/profile/password.html", title="Edit Password", form=form)

app/templates/includes/app_footer.html
<footer class="main">
    &copy; 2024 <strong>{{ config["TITLE"] }}</strong> {{ config["BRIEF"] }} by <a href="{{ url_for("main.about") }}" target="_blank">{{ config["AUTHOR"] }}</a>
    <br>
    {{ config["TITLE"] }} is an open source project. Visit the <a href="https://github.com/emregeldegul/dolphin" target="_blank">github</a> repo to contribute.
</footer>

app/templates/includes/app_header.html
<header class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <!-- logo -->
        <div class="navbar-brand">
            <a href="{{ url_for("collection.collection_index") }}">
                <img src="{{ url_for("static", filename="assets/images/dolphin_logo.png") }}" width="120" alt="" style="opacity:0.4;filter:alpha(opacity=40)" onmouseover="this.style.opacity=1;this.filters.alpha.opacity=100" onmouseout="this.style.opacity=0.4;this.filters.alpha.opacity=40"/>
            </a>
        </div>
        <!-- main menu -->
        <ul class="navbar-nav">
            {% if current_user.is_authenticated %}
                <li class="has-sub">
                    <a href="{{ url_for("collection.collection_index") }}">
                        <i class="entypo-home"></i>
                        <span class="title">Home Page</span>
                    </a>
                </li>
                <li class="active has-sub">
                    <a href="{{ url_for("collection.collection_index") }}">
                        <i class="entypo-bag"></i>
                        <span class="title">My Collections</span>
                    </a>
                </li>
                <li class="has-sub">
                    <a href="{{ url_for("main.public_collections") }}">
                        <i class="entypo-share"></i>
                        <span class="title">Public Collections</span>
                    </a>
                </li>
            {% else %}
                <li class="active has-sub">
                    <a href="{{ url_for("main.index") }}">
                        <i class="entypo-home"></i>
                        <span class="title">Home Page</span>
                    </a>
                </li>
                <li class="has-sub">
                    <a href="{{ url_for("auth.login") }}">
                        <i class="entypo-user"></i>
                        <span class="title">Login</span>
                    </a>
                </li>
                <li class="has-sub">
                    <a href="{{ url_for("auth.register") }}">
                        <i class="entypo-user-add"></i>
                        <span class="title">Register</span>
                    </a>
                </li>
                <li class="has-sub">
                    <a href="{{ url_for("main.public_collections") }}">
                        <i class="entypo-share"></i>
                        <span class="title">Public Collections</span>
                    </a>
                </li>
            {% endif %}
        </ul>
        <!-- notifications and other links -->
        <ul class="nav navbar-right pull-right">
            {% if current_user.is_authenticated %}
                <!-- raw links -->
                <li class="dropdown">
                <li>
                    <a href="{{ url_for("profile.index") }}">{{ current_user.full_name }}</a>
                </li>
                <li class="sep"></li>
                <li>
                    <a href="{{ url_for("auth.logout") }}">
                        Log Out <i class="entypo-logout right"></i>
                    </a>
                </li>
            {% endif %}
            <!-- mobile only -->
            <li class="visible-xs">
                <!-- open/close menu icon (do not remove if you want to enable menu on mobile devices) -->
                <div class="horizontal-mobile-menu visible-xs">
                    <a href="#" class="with-animation"><!-- add class "with-animation" to support animation -->
                        <i class="entypo-menu"></i>
                    </a>
                </div>
            </li>
        </ul>
    </div>
</header>

app/templates/includes/app_menu.html
<div class="panel panel-primary" data-collapsed="0">
    <div class="panel-body">
        <div id="list-1" class="nested-list dd with-margins">
            <ul class="dd-list">
                <li class="dd-item">
                    <a href="{{ url_for("collection.collection_create") }}" class="btn btn-block btn-primary">Create Collection</a>
                    <hr>
                    <div class="dd-handle">
                        <i class="entypo-bag"></i> <a href="{{ url_for("collection.collection_index") }}">All Collections</a>
                    </div>
                    <div class="dd-handle">
                        <i class="entypo-ticket"></i> <a href="{{ url_for("collection.collection_index", type="unlabeled") }}">Unlabeled Collections</a>
                    </div>
                    <div class="dd-handle">
                        <i class="entypo-pencil"></i> <a href="{{ url_for("collection.tag_index") }}">Manage Tags</a>
                    </div>
                    <hr>
                    {% for menu_tag in menu_tag_navigation %}
                        <div class="dd-handle">
                            <i class="entypo-tag"></i> <a href="{{ url_for("collection.collection_index", tag=menu_tag.name) }}">{{ menu_tag.name }} ({{ menu_tag.active_collection_count() }})</a>
                        </div>
                    {% endfor %}
                </li>
            </ul>
        </div>
    </div>
</div>